# Generated by Django 4.1.6 on 2023-03-07 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_order_order_detail'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table='order_tb',
        ),
        migrations.AlterModelTable(
            name='order_detail',
            table='order_details',
        ),
    ]
