# Generated by Django 4.1.6 on 2023-02-08 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.BigIntegerField()),
                ('gender', models.CharField(max_length=15)),
                ('status', models.CharField(default='active', max_length=20)),
            ],
        ),
    ]
