# Generated by Django 4.1.6 on 2023-02-08 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_seller'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='seller',
            table='seller',
        ),
    ]
