# Generated by Django 4.1.6 on 2023-02-09 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_alter_seller_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='password',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='seller',
            name='user_name',
            field=models.IntegerField(default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='seller',
            name='holder_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='seller',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
