# Generated by Django 4.1.6 on 2023-02-13 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_alter_seller_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='pic',
            field=models.ImageField(default='static/images/defaulimage.png', upload_to='seller/'),
        ),
    ]
